
name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v2

    - name: Create frontend env file
      run: |
        cd frontend
        touch .env
        echo  REACT_APP_API_URL=${{ secrets.API_URL }} >> .env
    - name: Build React App
      run: |
        cd frontend
        npm install
        npm run build

    - name: Create backend env file
      run: |
        cd backend
        touch .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env  
        echo ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} >> .env  
        echo MONGODB_URL=${{ secrets.MONGODB_URL }} >> .env    

    - name: Move Frontend Build to Backend
      run: |
        mv frontend/build backend/build
    - name: Install and Build Backend
      run: |
        cd backend
        npm install
        npm run test
        
    - name: Deploy to Render
      env:
        RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
      run: |
        cd backend
        render login --token $RENDER_API_TOKEN
        render deploy
